# Generated by Django 5.2.17 on 2026-09-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=50, unique=True, verbose_name='Номер лота')),
                ('production_spec', models.CharField(blank=True, max_length=200, null=True, verbose_name='Спецификация')),
                ('plan_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Плановое количество (Total)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Информация о лоте',
                'verbose_name_plural': 'Информация о лотах',
                'ordering': ['-lot_number'],
            },
        ),
        migrations.CreateModel(
            name='ManualDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs_no', models.CharField(max_length=100, verbose_name='Серийный номер БУ')),
                ('production_spec', models.CharField(blank=True, max_length=200, null=True, verbose_name='Спецификация')),
                ('lot_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер лота')),
                ('entry_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата поступления в производство')),
                ('reason', models.TextField(blank=True, verbose_name='Причина брака')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Кто добавил')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Ручной брак',
                'verbose_name_plural': 'Ручные браки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(db_index=True, max_length=50, verbose_name='Номер лота')),
                ('opno', models.CharField(blank=True, max_length=50, null=True, verbose_name='opno')),
                ('op_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название операции')),
                ('production_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер производства')),
                ('production_version', models.IntegerField(blank=True, null=True, verbose_name='Версия производства')),
                ('product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип продукта')),
                ('production_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название производства')),
                ('production_spec', models.CharField(blank=True, max_length=200, null=True, verbose_name='Спецификация')),
                ('subop_sequence', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер субоперации')),
                ('subop_no', models.IntegerField(db_index=True, verbose_name='Номер станции')),
                ('subop_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название станции')),
                ('position_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер позиции')),
                ('workstation_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя станции')),
                ('pcs_no', models.CharField(db_index=True, max_length=100, verbose_name='Серийный номер БУ')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя')),
                ('created_date', models.DateTimeField(db_index=True, verbose_name='Дата и время прохождения')),
                ('working_hours', models.IntegerField(blank=True, null=True, verbose_name='Рабочие часы')),
                ('result', models.CharField(blank=True, max_length=20, null=True, verbose_name='Результат')),
                ('test_data', models.TextField(blank=True, null=True, verbose_name='Тестовые данные')),
            ],
            options={
                'verbose_name': 'Запись производства',
                'verbose_name_plural': 'Записи производства',
                'ordering': ['created_date'],
                'indexes': [models.Index(fields=['pcs_no', 'subop_no'], name='production__pcs_no_23ebe4_idx')],
                'unique_together': {('pcs_no', 'subop_no', 'created_date')},
            },
        ),
        migrations.CreateModel(
            name='Report5Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs_no', models.CharField(max_length=100, verbose_name='Серийный номер БУ')),
                ('station_no', models.IntegerField(verbose_name='Номер станции')),
                ('lot_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер лота')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Кто добавил')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Комментарий отчета 5',
                'verbose_name_plural': 'Комментарии отчета 5',
                'ordering': ['-created_at'],
                'unique_together': {('pcs_no', 'station_no')},
            },
        ),
    ]
